### PR TITLE
Feature/upgrade to app router

### LINKED ISSUE #26: ウェブサイトをメンテナンス可能にする計画
### Pages routerはシンプルなアプリ向け:
　- このアプリケーションでは、サーバーサイドのコンポーネントの方がはるかに理にかなっている
　- https://medium.com/@jawaragordon/choose-your-own-adventure-next-js-app-vs-pages-router-528dbf25b37f
　- https://dev.to/dcs_ink/nextjs-app-router-vs-pages-router-3p57 
### JS vs TS:
  - TSは単純なタイプミスを避けるのに役立つ
  

PS: これは少し大きいが、難しいステップではない
私がステップを通じて指導するミーティングをアレンジすることもできる。
リファクタリングを始めるのが早ければ早いほど、それは容易になる

## ステップの概要
- [ドキュメンテーション](https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration)
- [TS Config](https://nextjs.org/docs/pages/building-your-application/configuring/typescript) 

Roadmap:
- [x] Refactor the base structure
- [x] Add Typescript support
- [x] Add i18n
- [x] Add dark theme
- [x] Add article components
- [x] Create the base download page
- [x] Remove the white line under the fade (maybe put fade over the whole card)
- [x] Responsivity
  - [x] Add padding to the side on the mobile view 
  - [x] padding for the articles and heading
- [x] put copyright in line with floorp logo
- [x] center social sites
- [x] Create theme changing component for images
- [x] Connect back the i18n usage

### PR DESCRIPTION
**Pull request by joshika39**
Closes #26

### CODE REVIEW

**Comment by itta611** [comment]
Great job! I love the parallax effect.
I'll start reviewing this shortly.

For your next OSS contribution, consider splitting your PRs to make it easier to review :)
Thanks!

**Comment by joshika39** [comment]
今マージに準備できています
レビュー後に統合します

**Comment by itta611** [comment]
Also, the layout is a bit messy.
Could you fix the layout and specs (e.g. font-size, width) of both pages the same as now?

<p>


</p>

Thanks!

**Comment by joshika39** [comment]
Please check it again

Thank you!

**Comment by joshika39** [comment]
@itta611 
Can we switch to npm from yarn?
The sharp package for image optimization is works better with npm then yarn.

What do you think?

**Comment by joshika39** [comment]
@itta611 
Is it okay if I merge it?

The layout is fixed, and the translation docs is also finished.

**Comment by itta611** [comment]
No, the codes are getting better, but the design has some strange parts (especially in the header).
So, could you please make the header component **exactly the same design** for now?

Also, the issues that I have pointed out in the review above have not been fixed yet.

**Comment by joshika39** [comment]
@itta611 

image
I rather not change change it to the previous header. That does **not** supports:
- responsive layout
- theme change
- language change

Please explain why do you want me to remove those from the new one?

Every component follows a `max-w-4xl (56rem)` width. if you check in inspect element:
image

Thanks!

**Comment by itta611** [comment]
Ah, maybe you are talking about nav bar, not header, aren't you?

**Comment by joshika39** [comment]
Hello @itta611,

Please check the current version here:
https://devtest.kou-gen.net/

I would not delay the merge so much longer.

Thank you!

**Comment by regularenthropy** [comment]
It's maybe only on my side, but the dark theme is way too dark.

**Comment by joshika39** [comment]
I had my reasons, for example if somebody has an OLED screen where the back pixels actually turn off, you have to make it completely black.

Also, as you said, it is also a bit preference of mine as well. I am following a pattern of these sites:
- https://github.com/
- https://nextjs.org/
- https://ui.shadcn.com/

All of these sites are in support for the true oled screens

But as always, I am open to suggestions.

**Comment by regularenthropy** [comment]
image
Also subjective, but I don't think that the dark blue on front (articles) is a good match to a black background. Would like to hear Itta's opinion on this.

**Comment by joshika39** [comment]
Thank you for the comment!

Totally forgot about those, that was unintentional..

**Comment by regularenthropy** [comment]
> Thank you for the comment!
> 
> Totally forgot about those, that was unintentional..
> 
> But if we're at it. can it be just black with the border or gray?

More of a dark gray with some border. Pure black with border is too boring

**Comment by regularenthropy** [comment]
image
Regarding animation: Could you please replace linear motion on "with Floorp" with ease in?

**Comment by joshika39** [comment]
@regularentropy, @itta611 

I made the ui changes, ready to be checked again. I tried the dark gray bg also some colors to pop stuff out

**Comment by regularentropy** [comment]
Awesome! We're getting there.
1) Please speed up the ease-in/out
2) Also, the colour pallet is too contrasted here.  image
image

@itta611 What do you think?

**Comment by joshika39** [comment]
@regularentropy 
What do you mean by contrasted? I am not at home in UI Design

**Comment by joshika39** [comment]
@regularentropy, @itta611 

Sorry for the many mentions!!

My docker image had done building you can test out the fixed version here: https://devtest.kou-gen.net

Here's my proposal: Let's merge it asap, the more it will be lengthened the more fixes will be needed.
After it have been merged, I'll go through it and create the necessary issues from the leftover stuff (if there is such things).

Thank you for your help and understanding!

PS.: Meaning behind my rush is that the whole project was rewritten and as it became open source people might start submitting PRs but my PR flipped the project on its head. That's why we can't pull this so much longer

**Comment by joshika39** [comment]
@itta611, @regularentropy 

Yesterday every design flaw was fixed, if you don't mind, I would merge this PR.

I'm just waiting for a feedback.

Thanks!

**Comment by regularentropy** [comment]
Alright, let's see how it'll go.

I reviewed it once again, and the new site looks great on both desktop and mobile.

Merging it in dev. Will deploy to main till the end of this month.

**Review by regularentropy — APPROVED** [review]

**Comment by joshika39** [comment]
Please, don't squash the commits!

**Pull request merged**
